kind: pipeline
name: default

steps:
- name: build and publish
  image: plugins/docker
  pull: always
  settings:
    repo: askiiart/tinyfeed
    tags: latest
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password